### PR TITLE
Move planning_ros_msgs to be an external dependency

### PR DESCRIPTION
**Pull request by ljarin**
In order to address #133, it is useful for the messages used by the planner to be independent from the rest of the stack so that kr_mav_control can link against them.

* rename planning_ros_msgs -> kr_planning_msgs
* rename planning_ros_utils -> kr_planning_rviz_plugins
* remove both of the above from kr_autonomous flight 
* move primitive_ros_utils (converts btw MPL and kr_planning_msgs) to the action_planner since it is only used there
* left for separate PR todo: data_type.h (defines common datatypes like Vec3f) and data_ros_utils (random data conversions) should not live in kr_planning_rviz_plugins, and should be in some common location. data_type is also copied from mpl/jps. state_machine, action_trackers, and action_planner are the packages that use data_ros_utils

### CODE REVIEW

**Comment by versatran01** [comment]
Can you also post links to the new packages?

**Comment by XuRobotics** [comment]
Great! Thanks, Laura. Once you add to the external and fix the CI issue, I will clean-build and test it on my side, before we merge.

**Comment by ljarin** [comment]
@versatran01  https://github.com/KumarRobotics/kr_planning_msgs

**Comment by ljarin** [comment]
OK, @XuRobotics and @versatran01 , sorry leaving this open for so long, but I think it is ready for a test.

The only thing remaining that I did not do is move https://github.com/KumarRobotics/kr_planning_msgs/blob/main/kr_planning_rviz_plugins/include/kr_planning_rviz_plugins/data_ros_utils.h and https://github.com/KumarRobotics/kr_planning_msgs/blob/main/kr_planning_rviz_plugins/src/utils/data_ros_utils.cpp to somewhere more logical/remove them from kr_planning_msgs repo. But I can do that if you think it shouldn't be merged without that.

**Comment by ljarin** [comment]
Also I assume the docker build github action should be run? I'm not sure how to trigger that?

**Comment by versatran01** [comment]
This is too big for a proper review. Since it's just moving stuff around, if it builds and works we can go ahead and merge it.
One thing I want to add is that data_type.h and data_ros_utils.h in kr_planning_msgs have no namespace, better to add one to prevent pollution of the global namespace and may cause resolution issues with stuff in jps/mpl.

**Comment by ljarin** [comment]
I think you mean https://github.com/KumarRobotics/kr_autonomous_flight/blob/master/autonomy_core/map_plan/mpl/include/mpl_basis/data_type.h as the 3rd one

**Comment by ljarin** [comment]
Yes, I agree...On the other hand there's only little name alias statements in that file. 

The easiest solution would be one copy in kr_planning_msgs, which doesn't make too much sense.

But sounds good if we're punting that for later.

**Comment by ljarin** [comment]
I will add a namespace for data_ros_utils

**Comment by versatran01** [comment]
This is just a personal preference but the namespace kr_planning_rviz_plugins has 24 characters and is a bit too long. 
Maybe we could just use our organizational namespace kr. For example 
https://github.com/KumarRobotics/kr_utils/blob/master/kr_math/include/kr_math/pose.hpp

**Comment by ljarin** [comment]
Sure, I don't feel strongly

In the meanwhile I have discovered a small rviz bug that I will resolve before we merge

**Comment by ljarin** [comment]
I found a bug in the rviz plug-in right before I left. Will address this weekend, sorry 😔

**Comment by tdinesh** [comment]
> I found a bug in the rviz plug-in right before I left. Will address this weekend, sorry pensive

Ping @ljarin

**Comment by ljarin** [comment]
So I finally reimplemented the missing visualization features (https://github.com/KumarRobotics/kr_planning_msgs), would it be possible to give this a try @XuRobotics @fcladera ?

**Review by shaoyifei96 — APPROVED** [review]
Tested gazebo full simulation with MPL.

**Pull request merged**
