### PR TITLE
Add Parameters to VoxelMap.msg

### PR DESCRIPTION
**Pull request by ankit16-py**
Added the variables, `val_occ, val_even, val_unknown, val_free, val_add and val_default` to `VoxelMap.msg` file with their default value. Subsequently replaced hard-codings of all these variables in `map_utils.h` files of the `mpl `and `jps3d` packages, `voxel_mapper.h` file from `mapper` package and `global_plan_server.cpp` and `local_plan_server.cpp` files from `action_planner` package

### CODE REVIEW

**Comment by fcladera** [comment]
Checks seem to be failing. This is a problem on our end.

**Comment by versatran01** [comment]
I very much hope that Jo’s does not depends on planning_ros_msgs

**Comment by versatran01** [comment]
Here are a few high-level points:

1. JPS should not depend on planning_ros_msgs. 
2. voxel values should not be hardcoded in msg as well, they should be fields, which can be assigned during msg creation. These values should be set in a parameter yaml file read by the mapper.
3. Main APIs in JPS/MPL should then be augmented to take these values as parameters.

This task is highly non-trivial, you need to look into many files in JPS/MPL to understand how things work. 
If you are not familiar with C++, then it is unlikely to fix this in one go.
Therefore, I suggest a preliminary task, which is to add back some of the tests I removed from JPS/MPL. https://github.com/KumarRobotics/jps3d/tree/master/test

Once the tests are in place, you can then proceed to make these voxel values (val_occ,...) input parameters to functions like setMap() https://github.com/KumarRobotics/kr_autonomous_flight/blob/d510ae20ebca88b277ec6f7af0d7b0092603d102/autonomy_core/map_plan/jps3d/include/jps/map_util.h#L82

**Comment by fcladera** [comment]
@ankit16-py please rebase on `origin/master` and force push to this branch.

**Comment by XuRobotics** [comment]
> @ankit16-py please fetch, rebase on `origin/master` and force push to this branch.

Good point, I will do this after I merge the other PR.

**Review by XuRobotics — COMMENTED** [review]
Looks good, I am going to test it before approving.

**Review by XuRobotics — APPROVED** [review]

**Comment by XuRobotics** [comment]
Approving the changes now, but Chao's suggestions need to be considered, probably we will create a new PR for this.

**Pull request merged**
